[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "orbit"
readme  = "README.md"

# TODO: Change your package specifications
# -----------------------------------------------------------------
title = "Extension Template"
author = "Fangtai Guo"
maintainer = "Fangtai Guo"
maintainer_email = "guofangtai@zhejianglab.com"
description="Extension Project of Multi robot for Orbit"
repository = "https://github.com/gftww/orbit.mrobot.git"
keywords = ["extension", "template", "orbit"]
# -----------------------------------------------------------------

[dependencies]
"omni.isaac.orbit" = {}
"omni.isaac.orbit_assets" = {}
"omni.isaac.orbit_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
# TODO: Change your package name
# -----------------------------------------------------------------
name = "orbit.mrobot"
# -----------------------------------------------------------------

[orbit_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
